/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Account: { // root type
    address: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Comment: { // root type
    contentURI: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    mediaURI?: string | null; // String
    text?: string | null; // String
    tokenId: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Edge: { // root type
    cursor?: string | null; // String
    node?: NexusGenRootTypes['Profile'] | null; // Profile
  }
  Follow: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    handle: string; // String!
    id: number; // Int!
    imageURI?: string | null; // String
    originalHandle: string; // String!
    tokenId: string; // String!
  }
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage?: boolean | null; // Boolean
  }
  Profile: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    default: boolean; // Boolean!
    handle: string; // String!
    id: number; // Int!
    imageURI?: string | null; // String
    originalHandle: string; // String!
    owner: string; // String!
    tokenId: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: {};
  Response: { // root type
    edges: Array<NexusGenRootTypes['Edge'] | null>; // [Edge]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Account: { // field return type
    address: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    profiles: Array<NexusGenRootTypes['Profile'] | null>; // [Profile]!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Comment: { // field return type
    contentURI: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    mediaURI: string | null; // String
    text: string | null; // String
    tokenId: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Edge: { // field return type
    cursor: string | null; // String
    node: NexusGenRootTypes['Profile'] | null; // Profile
  }
  Follow: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    handle: string; // String!
    id: number; // Int!
    imageURI: string | null; // String
    originalHandle: string; // String!
    tokenId: string; // String!
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean | null; // Boolean
  }
  Profile: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    default: boolean; // Boolean!
    followers: Array<NexusGenRootTypes['Follow'] | null>; // [Follow]!
    following: Array<NexusGenRootTypes['Follow'] | null>; // [Follow]!
    handle: string; // String!
    id: number; // Int!
    imageURI: string | null; // String
    originalHandle: string; // String!
    owner: string; // String!
    tokenId: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: { // field return type
    getMyAccount: string | null; // String
    getProfile: NexusGenRootTypes['Profile'] | null; // Profile
  }
  Response: { // field return type
    edges: Array<NexusGenRootTypes['Edge'] | null>; // [Edge]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
}

export interface NexusGenFieldTypeNames {
  Account: { // field return type name
    address: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    profiles: 'Profile'
    updatedAt: 'DateTime'
  }
  Comment: { // field return type name
    contentURI: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    mediaURI: 'String'
    text: 'String'
    tokenId: 'String'
    updatedAt: 'DateTime'
  }
  Edge: { // field return type name
    cursor: 'String'
    node: 'Profile'
  }
  Follow: { // field return type name
    createdAt: 'DateTime'
    handle: 'String'
    id: 'Int'
    imageURI: 'String'
    originalHandle: 'String'
    tokenId: 'String'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
  }
  Profile: { // field return type name
    createdAt: 'DateTime'
    default: 'Boolean'
    followers: 'Follow'
    following: 'Follow'
    handle: 'String'
    id: 'Int'
    imageURI: 'String'
    originalHandle: 'String'
    owner: 'String'
    tokenId: 'String'
    updatedAt: 'DateTime'
  }
  Query: { // field return type name
    getMyAccount: 'String'
    getProfile: 'Profile'
  }
  Response: { // field return type name
    edges: 'Edge'
    pageInfo: 'PageInfo'
  }
}

export interface NexusGenArgTypes {
  Query: {
    getProfile: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}